### ISSUE TITLE
Add regression test for wish activity/fragment

### ISSUE THREAD

**Issue by ironjan** [ironjan/metal-only#135]
**TODO**
* [ ] Decide how to test this: UI espresso, view unit tests,...
* [ ] Add test for "unlimited wishes/greetings"
* [ ] Add test for "limited wishes, limit not reached"
* [ ] Add test for "limited wishes, limit reached"
* [ ] Add test for "limited greetings, limit not reached"
* [ ] Add test for "limited greetings, limit not reached"
